bigboringsystem/bigboringsystem

lib/posts.js, test/test.js, views/discover.jade, views/posts.jade, views/user.jade
Fixes #56 
Land #82 first, though, this depends on it.
=> Canonical post urls

views/index.jade
=> Fixing a typo on the dashboard.

README.md, index.js, lib/conf.js
Fixes the issue in bigboringsystem/bigboringsystem#107 and makes local dev slightly nicer, eliminating the local.json file requirement and printing out server connection info on successful connection.
=> Server defaults

index.js, public/styl/global.styl
Not sure if/how you want to handle logging the stack, I could hide that behind a `dev` flag or an environment variable if you want?
=> Fix #114: Output error message

lib/profile.js, package.json
=> Adding hoek to the project to escape strings.

index.js, lib/services.js, views/index.jade, views/privacy.jade
This lets people know how their info is used, not gonna sell it/share it with third parties, etc
I have some word wrap work to do. My old startup buddy gave me permission to use this policy from a system we built. I've modified it to reflect BBS.  It's a bit long, but there's not much legalese and it covers all the typical stuff that we do with webapps, including explicitly not selling/trading/renting people's personal information to third parties.
=> Include a privacy policy for BBS 

package.json
@jasonrhodes this fixed this for me
=> force 1.0.4 for gulp-nodemon #146

test/test.js, views/post.jade
added a couple more tests to make sure authed users and reply and unauthed users cannot
=> remove ability for unauthed users to reply to posts #142

views/authenticate.jade
=> Added autofocus attribute to the pin input on the authentication page.

lib/auth.js, lib/pin.js, lib/profile.js, lib/utils.js, scripts/migrate-phone-numbers.js
also has TODOs for @imakewebthings to add his hashing calls
=> migration script for converting all user numbers

test/test.js
old test was broken for verifying if authorized user can actually reply to a post or not, fixing that test with a valid one
=> fix test from pull request #163

index.js, lib/posts.js, package.json, test/test.js
#106 feed can be found at host/rss
=> added rss feed for discover page

index.js, test/test.js, views/error.jade
Otherwise, our "post not found" 404 looks a lot like a 500 random server error.
Fixes #139 
Review? @coleGillespie @jasonrhodes
=> Show error codes and standard http messaging for errors

CONTRIBUTING.md
I wanted to add some info about rebasing and squashing, but then I just decided to add info about how to do a PR and some slight reorganization of the file. 
See the formatted doc, as updated, here: https://github.com/jasonrhodes/bigboringsystem/blob/rebase-squash-help/CONTRIBUTING.md
=> Added instructions and slight reorg of CONTRIBUTING doc

public/js/chat.js, public/styl/global.styl
Covers: https://github.com/bigboringsystem/bigboringsystem/issues/39
A favicon notification was mentioned and sort of attached to #39, but I'd like to break that into its own issue.
Styles can totally be updated further down the line. Would just like to get this out the door now.
=> Username highlighting

index.js, package.json, views/chat.jade, views/layout.jade, views/posts.jade
=> Cache bust CSS and JS using server start timestamp

lib/auth.js, lib/pin.js, lib/services.js, local.json-dist, test/fixtures.json, test/test.js, views/index.jade
=> toggle signups

views/post.jade
This formats the permalink for post replies the same way as timestamp on the discover page.
=> nicer reply timestamp link

.dockerignore, Dockerfile, README.md
This include a Dockerfile, a .dockerignore, and documentation.
It relies on #74 in order to build the styles without running nodemon.
I think this could still be made more elegant, and am open to suggestions.
This most likely should no be merged yet, but I think it is a good first step towards making it easier for other people to deploy
/cc @ednapiranha @isaacs
=> First Pass at Docker

views/layout.jade
=> Add RSS link in head

index.js, lib/mute.js, lib/services.js, public/js/chat.js, test/test.js, views/chat.jade, views/user.jade
This mutes users on the chat so you cannot see them appear on the sidebar, nor can you see their messages. Note that I did not make it mute their posts - this might be relevant for having to delete content or reporting it.
=> mute functionality for chat

lib/services.js, views/index.jade, views/layout.jade, views/links.jade, views/privacy.jade
Rebasing and quick fix of #179, thanks again to @jonursenbach for the original work.
=> User session now loaded on /privacy
