lib/posts.js
Previously this deleted all posts with the same creation time as the
user's posts.
=> Fix: Don't delete other users' posts when deleting a user account

.gitignore, index.js, lib/auth.js, lib/ban.js, lib/conf.js, lib/db.js, lib/pin.js, lib/posts.js, lib/profile.js, lib/services.js, lib/utils.js, local.json-dist, package.json, test/db/.gitignore, test/test.js
The better to override in tests, and DRY up a bunch of duplicated code.
It feels like lib/db.js should be some kind of dedicated "manage
multiple levelDBs in a single folder" module or something, but there's a
lot of BBS-specific stuff in there.  I'm not level-savvy enough to
confidently predict what other users might want in such a module, so I'm
tempted to just leave it as-is for the next brave soul to figure out.
Configuring the location of the db root folder is super important,
though.  Now, you could very easily start the server with something like
`node index.js --db /var/db/bbs` (or env or local.json) and it'll put
all the levels in there.  For tests, this makes it easy to wipe the db's
out and not accidentally the non-test databases.
Fixes #67
=> Refactor db to a single module, folder, conf value

index.js, lib/profile.js, package.json, test/test.js, views/profile.jade
This adds the routes `/profile/export.json` and `/profile/export.csv`. They export the current user's posts in the respective format. Includes tests! :sparkles:
=> Add posts export (Fixes GH-98)

package.json
it was included in commit [440360e](https://github.com/joates/bigboringsystem/commit/440360e020f85d4d240e338abd33f88f266f9c37#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) but is not currently used in tests.
=> removed package 'nock' from devDependecies

local.json-dist
IMO it's confusing to have a sample operator by default, since this line will evaluate to true and cause weird issues on first time run: https://github.com/bigboringsystem/bigboringsystem/blob/master/lib/services.js#L20
This way, `npm start` will actually run properly locally after adding Twilio credentials
=> Remove default for ops

views/layout.jade
I've been lurking on BBS for a bit and I know this is super nitpicky, but this corrects "Digital Ocean" as "DigitalOcean". One of my... enterprising... colleagues even made our internal SlackBot fix this internally!
The community is cool so far, looking forward to making some actual posts soon!
=> Digital Ocean => DigitalOcean

lib/posts.js, views/posts.jade
I noticed that the error message page doesn't actually display error messages, but perhaps that should be a new ticket?
=> Fix #111: Prevent blank posts

.eslintrc-frontend, lib/auth.js, lib/pin.js, lib/profile.js, lib/twilio.js, package.json, public/js/chat.js, public/js/global.js
This patch closes #117 
It adds an npm script to lint the front end code in ```public/js```.  It also adds the linting step to ```npm test```.  Now linting will be part of the travis CI process, and all code will be nice and tidy.
=> Add linting to CI / Testing

README.md, lib/conf.js, lib/pin.js, lib/services.js, views/authenticate.jade, views/layout.jade
This solves a few issues:
1. A bug introduced in my earlier PR that won't let you log in without an ops array as a default value
1. Removes the pin being output to the console on generation, since that was for dev mode and we now just check against the fixture pin
1. Easier for people to get it up and running with dev mode messages (see below images)
Homepage: http://cl.ly/image/440u36162b3K
Login with pin page: http://cl.ly/image/1I1o0s2q3S36
=> Better pin info for users in dev mode

index.js, lib/posts.js, lib/profile.js, public/styl/global.styl, test/test.js, views/post.jade, views/posts.jade, views/profile.jade
This has come along to a point where I think it's worth discussing.
This adds basic reply tracking, and puts very minimal links to in-system replies under each post.
You can choose to track replies on a per-post level.  The `showreplies` field defaults based on a profile setting.  (Default is "do not track replies by default".)
The author can delete the reply links from their posts if they want them gone.  (Of course, you can't *change* the reply-tracking behavior of a post without deleting and re-posting, since this would be an edit, and thus verboten.)
I'd like to also add the ability to block reply links from specific users.  However, I think that would be better approached as part of a larger "hide this user from me" feature.
No data migration required.  All existing posts will not …
=> Show replies beneath post

lib/auth.js, test/test.js
when a new user gets created make show replies the default so that the check boxes are checked on both profile and posts page
=> showreplies added on new user creation #140

lib/services.js
Fixes #144.  If a UID is provided in the package.json that does not exist in the db the app would 404 on the main page.  This is no longer the case, the op with the invalid UID is just ignored
=> Fix 404 when invalid op id provided in local.json

views/profile.jade
This is a fix for #154. Now that names are stored in escaped form they need to be unescaped before use inside an attribute. This change uses Jade's `!=` attribute unescape syntax to do that.
Before:
1. Change name in profile to `~~` and save. Note name is displayed in the escaped form, `&#x7e;&#x7e;`.
2. Save again without making changes. The escaped entity is then escaped again.
With change:
The name is displayed as `~~` after save. Subsequent saves do not go into an escaping spiral of doom.
=> Unescape name when displaying it back in the profile form

index.js
Loop through remaining open sockets when a user disconnects from chat. If a socket with the same user UID as the disconnecting socket is found, do not remove that user from the chat list. This means the user has another tab/window with chat open.
Fixes #160.
=> Check for duplicate socket UIDs on chat disconnect

lib/auth.js, lib/profile.js, lib/utils.js, local.json-dist, scripts/hash-phone-numbers.js, views/profile.jade
For use in our migration scripts and future phone hashings. Adds `phoneSalt` to config file.
This also now includes commits to hash the primary phone numbers, as well as hash the secondary phone numbers + store the last 2 digits for display purposes.
=> Add phoneSalt config and phone hashing utility function

views/chat.jade
For if you're switching around tabs, because autofocus only applies on the initial render.
=> Fast focusing on the chat input

public/js/global.js
Fixes #195 where Firefox wasn't getting date formatting. `innerText` is non-standard.
=> Use textContent instead of innerText for setting date strings

public/js/chat.js
Many people have really long usernames with emoticons in them. This just shows the full username when you hover over their name in the sidebar.
=> Show full username in chat on hover in sidebar

lib/services.js
Fixes #214. Every view requires a context object, event if it's empty.
=> Fix missing context in privacy view rendering

public/js/chat.js
There was a small bug in chat where people with complex (i.e. emoticon) names would not have their own name highlighted when they got a message. This is a fix!
=> Allow names with unicode and special characters to be highlighted.
